Validating/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^',include('apps.dating_app.urls',namespace='dating'))
]

apps/dating_app/urls.py
from django.conf.urls import url
from views import *

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^create_user$',create_user,name='create_user'),
	url(r'^login_user$',login_user,name='login_user'),
	url(r'^home$',home,name='home'),
	url(r'^logout$',logout,name='logout'),
	url(r'^show_user/(?P<user_id>\d+)$',show_user, name='show_user'),
	url(r'^edit_user/(?P<user_id>\d+)$',edit_user, name='edit_user'),
	url(r'^update_user/(?P<answer_id>\d+)$',update_user, name='update_user'),
	url(r'display_questions$',display_questions,name='display_questions'),
	url(r'^questions$',questions,name='questions'),
	url(r'^find_matches$',find_matches,name='find_matches'),
	url(r'^upload_pic$',upload_pic,name='upload_pic'),
	url(r'^new_message/(?P<receiver_id>\d+)$',new_message, name='new_message'),
	url(r'^create_message/(?P<receiver_id>\d+)/(?P<conversation_id>\d+)$',create_message,name='create_message'),
	url(r'^show_my_messages/(?P<user_id>\d+)$',show_my_messages,name='show_my_messages'),
	url(r'^like_user/(?P<user_id>\d+)$',like_user,name='like_user'),
	url(r'^unlike_user/(?P<user_id>\d+)$',unlike_user,name='unlike_user'),
	url(r'^preference$',preference, name='preference'),
	url(r'^edit_preference$',edit_preference, name='edit_preference'),
	url(r'^delete_message/(?P<message_id>\d+)$',delete_message,name='delete_message'),
	url(r'^delete_pic/(?P<image_id>\d+)$',delete_pic,name='delete_pic'),
	url(r'^change_profile_pic/(?P<image_id>\d+)$',change_profile_pic,name='change_profile_pic'),
	url(r'^search$', search_query, name='search'),

]

apps/dating_app/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class User(models.Model):
	name = models.CharField(max_length=50)
	username = models.CharField(max_length=50, unique=True)
	email = models.EmailField(unique=True)
	password = models.CharField(max_length=200)
	age = models.IntegerField()
	account_active = models.BooleanField(default=True)
	profile_pic_url = models.FileField(upload_to='img',default='img/user.png')
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

class Answer(models.Model):
	gender = models.CharField(max_length=10)
	height = models.FloatField()
	feet = models.IntegerField()
	inches = models.IntegerField()
	language = models.CharField(max_length=10)
	zip_code = models.IntegerField()
	stack = models.CharField(max_length=15)
	religion = models.CharField(max_length=10)
	smoke = models.BooleanField(default=False)
	body_type = models.CharField(max_length=20)
	ethnicity = models.CharField(max_length=20)
	wants_children = models.BooleanField()
	about_you = models.TextField(max_length=1000)
	user = models.OneToOneField(User, related_name='my_answers')
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

class Preference(models.Model):
	gender = models.CharField(max_length=10)
	height = models.FloatField()
	feet = models.IntegerField()
	inches = models.IntegerField()
	language = models.CharField(max_length=10)
	zip_code = models.IntegerField()
	stack = models.CharField(max_length=15)
	religion = models.CharField(max_length=10)
	smoke = models.BooleanField(default=False)
	body_type = models.CharField(max_length=20)
	ethnicity = models.CharField(max_length=20)
	wants_children = models.BooleanField()
	about_you = models.TextField(max_length=1000)
	user = models.OneToOneField(User, related_name='my_preferences')
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

class Match(models.Model):
	user1 = models.ForeignKey(User, related_name='my_match')
	user2 = models.ForeignKey(User, related_name='matched_me')
	percent_match = models.IntegerField()
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

class Like(models.Model):
	user1 = models.ForeignKey(User, related_name='my_likes')
	user2 = models.ForeignKey(User, related_name='liked_me')
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

class Conversation(models.Model):
	user1 = models.ForeignKey(User, related_name='my_conversation1')
	user2 = models.ForeignKey(User,related_name='my_conversation2')
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

class Message(models.Model):
	conversation = models.ForeignKey(Conversation,related_name='messages')
	text = models.TextField(max_length=1000)
	sender = models.ForeignKey(User, related_name='my_sent')
	receiver = models.ForeignKey(User,related_name='my_received')
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

class Image(models.Model):
	user = models.ForeignKey(User,related_name='my_pic')
	user_pic = models.FileField(upload_to='img',default='img/user.png')
	profile_pic = models.BooleanField(default=False)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

class Like(models.Model):
	like1 = models.ForeignKey(User, related_name='liker')
	like2 = models.ForeignKey(User, related_name='likee')
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

apps/dating_app/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.core.urlresolvers import reverse, resolve
from django.contrib.postgres.search import SearchQuery, SearchRank, SearchVector
from itertools import chain
from urlparse import urlparse
from django.db.models import Q
from .models import *
import bcrypt, re
import json
import urllib2

from django.conf import settings
from django.core.files.storage import FileSystemStorage

# Login and Registration
def index(request):
	if 'username' in request.session:
		print '-' * 50
		print 'session:'
		print '[username]:',request.session['username']
		print '[user_id]:',request.session['user_id']
		print '-' * 50
	else:
		print '-' * 50
		print 'no user logged in'
		print '-' * 50
	return render(request, 'dating_app/login.html')

def create_user(request):
	# Create a new User using html form inputs from Index(login.html)
	server_name = request.POST['html_name']
	server_username = request.POST['html_username']
	server_email = request.POST['html_email']
	emailValid = re.search(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$',server_email)
	server_age = request.POST['html_age']
	server_password = request.POST['html_password']
	server_confirm_pw = request.POST['html_confirm_password']

	# Validate user input
	if len(server_name)<1 or len(server_username)<1 or len(server_email)<1 or len(server_age)<1 or len(server_password)<1 or len(server_confirm_pw)<1:
		messages.warning(request,'Please make sure no fields are blank')
		return redirect('dating:index')
	elif len(server_password)<6:
		messages.warning(request, 'password must be at least 6 characters')
		return redirect('dating:index')
	elif emailValid == None:
		messages.warning(request, 'invalid email format')
		return redirect('dating:index')
	elif server_password != server_confirm_pw:
		messages.warning(request,'passwords must match')
		return redirect('dating:index')
	else:
		# If valid, create new user
		try:
			hashed_pw = bcrypt.hashpw(server_password.encode("UTF-8"),bcrypt.gensalt())
			print '-' * 50
			print 'hashed pword successfully:', hashed_pw
			print '-' * 50
			new_user = User.objects.create(name=server_name,username=server_username,email=server_email,age=server_age,password=hashed_pw)
			default_pic = Image.objects.create(user=new_user,user_pic='img/user.png')
			print '-' * 50
			print 'created user successfully'
			print '-' * 50
			request.session['user_id'] = new_user.id
			request.session['username'] = server_username
			request.session['name'] = server_name

			# If creation successful, redirect to Home page
			return redirect('dating:display_questions')

		except:
			print '-' * 50
			print 'error hashing password or creating user'
			print '-' * 50
			messages.warning(request, 'hashing password or creating user')
			# If unsuccessful, redirect back to index, display errors
			return redirect('dating:questions')

def login_user(request):
	# If login fields match a User, insert session info, and redirect to Home page
	server_email = request.POST['html_email']
	server_password = request.POST['html_password']

	# Validate user input
	if len(server_email)<1 or len(server_password)<1:
		messages.warning(request, 'both login fields are required')
		return redirect('dating:index')
	elif len(server_password)<6:
		messages.warning(request, 'password must be at least 6 characters')
		return redirect('dating:index')
	else:
		# If valid, search the database for user
		try:
			this_user = User.objects.get(email=server_email)
			print '-' * 50
			print 'password',this_user.password
			print '-' * 50
			if this_user.password == bcrypt.hashpw(server_password.encode("UTF-8"),this_user.password.encode("UTF-8")):
				request.session['user_id'] = this_user.id
				request.session['username'] = this_user.username
				print '-' * 50
				print 'Login successful!'
				print 'CURRENT USER'
				print 'id:',request.session['user_id']
				print 'username:',request.session['username']
				print '-' * 50

				return redirect('dating:home')

			else: # email found but password does not match that email
				messages.warning(request, 'invalid password, try again')

				return redirect('dating:index')
		except: # no email matches what the user submitted
			messages.warning(request, 'user not found')

			return redirect('dating:index')

# Home Page
def home(request):
	print '-' * 50
	print 'CURRENT SESSION'
	print '[username]:',request.session['username']
	print '[user_id]:',request.session['user_id']
	print '-' * 50
	all_pics = Image.objects.filter(profile_pic=True)
	pic_dict = {}
	context = {
		'match': Match.objects.filter(user1_id = request.session['user_id']),
		'match2': Match.objects.filter(user2_id=request.session['user_id']),
		'all_users': User.objects.exclude(id=request.session['user_id']),
		'all_pics': all_pics,
	}

	return render(request, 'dating_app/home.html', context)

def logout(request):
	request.session.clear()
	return redirect('dating:index')

def show_user(request,user_id):
	this_user = User.objects.get(id=user_id)
	my_answers = Answer.objects.get(user_id=this_user.id)
	profile_pic = ""
	try: # find user's profile pic
		profile_pic_url = this_user.profile_pic_url
	except: # If no profile pic is found for this user, default image is shown
		profile_pic_url = 'img/user.png'
	try:
		like = Like.objects.get(like1_id=request.session['user_id'], like2_id=user_id)
	except:
		like = False
	my_likes = Like.objects.filter(like1_id=request.session['user_id'])

	# Gather all gallery pictures
	my_gallery = Image.objects.filter(user_id=this_user.id)
	context = {
		'user': this_user,
		'answers': my_answers,
		'like': like,
		'my_like': my_likes,
		'profile_pic': profile_pic_url,
		'my_gallery': my_gallery
	}
	return render(request, 'dating_app/show_user.html', context)

def edit_user(request,user_id):
	print 'user_id:',user_id
	print 'session[user_id]:',request.session['user_id']
	if str(user_id) != str(request.session['user_id']):
		messages.warning(request, 'You do not have permission to edit another user')
		return redirect('dating:home')
	else:
		this_user = User.objects.get(id=request.session['user_id'])
		my_answers = Answer.objects.get(user_id=this_user.id)
		context = {
			'user': this_user,
			'answers': my_answers
		}
		return render(request, 'dating_app/edit_user.html', context)

def update_user(request, answer_id):
	name = request.POST['html_name']
	username = request.POST['html_username']
	age = request.POST['html_age']
	gender = request.POST['html_gender']
	feet = request.POST['html_feet']
	inches = request.POST['html_inches']
	height = float(feet) + float(inches)/12
	language = request.POST['html_language']
	stack = request.POST['html_stack']
	religion = request.POST['html_religion']
	smoke = request.POST['html_smoke']
	body = request.POST['html_body_type']
	ethnicity  = request.POST['html_ethnicity']
	children = request.POST['html_wants_children']
	about_you = request.POST['html_about_you']

	# If any fields are blank, send back to edit_user
	if len(gender)<1 or len(str(height))<1 or len(language)<1 or len(stack)<1 or len(religion)<1 or len(smoke)<1 or len(body)<1 or len(ethnicity)<1 or len(children)<1 or len(about_you)<1:
		messages.warning(request, 'Make sure all fields are filled in')
		return redirect('dating:edit_user')
	else: # If valid, update answers
		Answer.objects.filter(id=answer_id).update(gender=gender,height=height, feet=feet, inches=inches,language=language,stack=stack,religion=religion,smoke=smoke,body_type=body,ethnicity=ethnicity,wants_children=children,about_you=about_you)
		User.objects.filter(id=request.session['user_id']).update(name=name,username=username,age=age)
		messages.success(request, 'Answers updated!')
		Match.objects.filter(user1_id=request.session['user_id']).delete()
		Match.objects.filter(user2_id=request.session['user_id']).delete()
		user = Answer.objects.get(id=request.session['user_id'])
		answer_exclude = Answer.objects.exclude(id=request.session['user_id'])
		user1zip = user.zip_code
		for ans in answer_exclude:
			counter = 0
			user2zip = ans.zip_code
			distance = find_distance(user1zip,user2zip)
			if ans.gender != user.gender:
				if ans.height > (user.height-10) and ans.height < (user.height-10):
					counter += 2
				if ans.zip_code == user.zip_code:
					counter += 3
				if distance <= 5:
					counter += 4
				if distance > 5:
					counter = counter - 1
				if ans.stack == user.stack:
					counter += 2
				if ans.religion == user.religion:
					counter += 3
				if ans.smoke == user.smoke:
					counter += 1
				if ans.body_type == user.body_type:
						counter += 3
				if ans.wants_children == user.wants_children:
					counter += 2
				if counter > 5:
					percent_match= (float(counter)/12)*100
					int(percent_match)
					Match.objects.create(user1_id = user.id, user2_id =ans.id, percent_match=percent_match)
		return redirect(reverse('dating:show_user',kwargs={'user_id': request.session['user_id']}))



def display_questions(request):
	return render(request, 'dating_app/questionaire.html')

def questions(request):
	gender = request.POST['html_gender']
	feet = request.POST['html_feet']
	inches = request.POST['html_inches']
	try:
		height = float(feet) + float(inches)/12
	except:
		messages.warning(request, 'Must include a height')
		return redirect('dating:display_questions')
	language = request.POST['html_language']
	stack = request.POST['html_stack']
	religion = request.POST['html_religion']
	zipcode = request.POST['html_zip_code']
	smoke = request.POST['html_smoke']
	body = request.POST['html_body_type']
	ethnicity  = request.POST['html_ethnicity']
	children = request.POST['html_wants_children']
	about_you = request.POST['html_about_you']
	if len(language)<1 or len(stack)<1 or len(religion)<1 or len(smoke)<1 or len(body)<1 or len(ethnicity)<1 or len(children)<1 or len(about_you)<1:
		messages.warning(request, 'Make sure all fields are filled in')
		return redirect('dating:display_questions')

apps/dating_app/templates/dating_app/header.html
<!DOCTYPE html>
<html>
<head>
	<title>ValiDating</title>
	{% load staticfiles %}
	<!-- Bootstrap CSS -->
	<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<!-- jQuery UI base theme-->
	<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css">
	<!-- jQuery -->
	 <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
	 <!-- jQuery -->
	 <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
	 <link rel="stylesheet" href="{% static 'dating_app/tinytools.toggleswitch.min.css' %}"></script>
	 <script src="{% static 'dating_app/tinytools.toggleswitch.min.js' %}"></script>
	 <!-- Bootstrap JS -->
	<script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	 <!-- Fonts -->
	<link href="https://fonts.googleapis.com/css?family=Pacifico|Open+Sans:300,600" rel="stylesheet">
	<!-- Custom Styles -->
	 <link rel="stylesheet" type="text/css" href="{% static 'dating_app/style.css' %}">
</head>
<body>
{% if messages %}
	{% for message in messages %}
		<p>{{message}}</p>
	{% endfor %}
{% endif %}
	<header class="row">
		<div class="col-sm-6 hidden-xs">
			<a href="{% url 'dating:home' %}">
			<div id="branding">
				<img class="img-responsive" src="{% static 'dating_app/ValiDate_logo.png' %}" alt="ValiDate Logo">
			</div>
		</a>
		</div> <!-- .col -->
		
		<!-- Main Navigation -->
		<!-- Hidden when screen is xs -->
		<div id="main_navigation hidden-xs" class="col-sm-6">
		<br><br>
			<nav >
			<a href="{% url 'dating:home' %}">Home</a>
			&nbsp;|&nbsp;
			<a href="{% url 'dating:show_user' user_id=request.session.user_id %}">View My Profile</a>
			&nbsp;|&nbsp;
			<a href="{% url 'dating:show_my_messages' user_id=request.session.user_id %}">My Messages</a>
			&nbsp;|&nbsp;
			<a href="{% url 'dating:logout' %}">Log out</a>
			
		</nav>
		</div> <!-- .col -->

		<!-- Mobile Navigation -->
        <!-- Appears only when screen size is 'xs' -->
        <div class="col-xs-12 visible-xs">
            <nav id="mobile-nav" class="navbar navbar-inverse visible-xs" role="navigation">
                <div class="container">
                
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#mobile-menu">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    </button>
                    <a href="{% url 'dating:home' %}">
                    <img src="{% static 'dating_app/logo.png' %}" alt="computer logo">
                    	<h1 class="branding">ValiDate.com</h1>
                </a>
                </div>
               

                <div class="collapse navbar-collapse" id="mobile-menu">
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'dating:home' %}">Home</a></li>
                        <li><a href="{% url 'dating:show_user' user_id=request.session.user_id %}">View My Profile</a></li>
                        <li><a href="{% url 'dating:display_questions' %}">Questionaire</a></li>
                        <li><a href="{% url 'dating:show_my_messages' user_id=request.session.user_id %}">My Messages</a></li>
                        <li><a href="{% url 'dating:logout' %}">Log out</a></li>
                    </ul>
                </div><!-- /.navbar-collapse -->
              <!-- /.container-fluid -->
            </nav> <!-- end Mobile Navigation -->
        </div>
		

	</header>

apps/dating_app/templates/dating_app/old_messages.html
{% for message in all_my_messages %}
		<div class="one_message">
			<label class="label label-success">From:</label>
			<a href="{% url 'dating:show_user' user_id=message.sender.id %}" class="message_username">
				{{message.sender.username}}
			</a>
			<br><br>
			<label class="label label-success">To:</label>
			<a href="{% url 'dating:show_user' user_id=message.receiver.id %}" class="message_username">{{message.receiver.username}}</a>
			<br><br>
			<p>
				<i class="label label-default">{{message.text}}</i>
				<a class="btn btn-danger" href="{% url 'dating:new_message' receiver_id=message.sender.id %}">Reply</a>

			{% if message.sender.id == request.session.user_id %}
				<form action="{% url 'dating:create_message' receiver_id=message.receiver.id %}" method="post">
			{% else %}
				<form action="{% url 'dating:create_message' receiver_id=message.sender.id %}" method="post">
			{% endif %}
				{% csrf_token %}
				<textarea name="html_message_text"></textarea>
				<br>
				<input class="btn btn-default" type="submit" value="Reply">
				<a class="btn btn-default" href="{% url 'dating:delete_message' message_id=message.id %}">Delete</a>
			</form>
			</p>

			
		</div> <!-- .one_message -->
	{% endfor %}

apps/dating_app/templates/dating_app/show_user.html
{% include 'dating_app/header.html' %}
	 {% load staticfiles %}

  <script>
  $( function() {
    $( ".progressbar" ).progressbar({
      value: 100
    });
  } );
  </script>

<div id="container-fluid">
	<div class="row">
		<!-- Left Sidebar -->
		<div id="show_user_sidebar" class="col-sm-2 center-block">
			<!-- Profile Picture -->
			<img class="img-responsive profile_pic" src="{% static 'dating_app/' %}{{profile_pic}}"  alt="{{ request.session.username }} profile pic">
			<br>

			<!-- If this is the current user's profile, show edit buttons -->
			{% if user.id == request.session.user_id %}
				<a class="btn btn-success center center-block" href="#file_upload">Change Image</a>
				<br>
				Account status: <br>
				<input type="checkbox" id="toggle_account">
				<br><br>
				<a class="btn btn-danger center-block" href="{% url 'dating:edit_user' user_id=request.session.user_id %}">Edit Profile</a><br>
				<a class="btn btn-danger center-block" href="{% url 'dating:edit_preference' %}">Edit Preferences</a>

			<!-- Or if this is not the current user's profile, show poke, message, etc. buttons -->
			{% else %}
			{% if not like %}
				<a class="btn btn-success center-block" href="{% url 'dating:like_user' user_id=user.id %}">Like Me</a>
				<br>
			{% elif like %}
			<a class="btn btn-warning center-block" href="{% url 'dating:unlike_user' user_id=user.id %}">Unlike Me</a>
			<br>
			{% endif %}
				<a class="btn btn-primary center-block" href="{% url 'dating:new_message' receiver_id=user.id %}">Message Me</a>

			{% endif %}

		</div> <!-- .col -->

		<!-- Main Content (Center) -->
		<div class="col-sm-8">
			<h1 class="page_heading">{{user.username}}</h1>
			<br>
			<span class="center center-block">100% complete</span>
			<div class="progressbar center-block hidden-sm"></div>
			<br>
			<!-- User's 'about_you' field might be blank, but if it's not, display its contents -->
			<p id="user_intro" class="center-block">
				{% if answers.about_you == "" %}
					Tell your potential matches more about yourself <a href="{% url 'dating:edit_user' user_id=request.session.id %}"> here </a>
				{% else %}
					{{answers.about_you}}
				{% endif %}
			</p>

			<!-- User Answers -->
			<div id="user_answers">
				<table>
					<tr>
						<td><label class="label label-info">Name:</label></td><td>{{user.name}}</td>
					</tr>
					<tr>
						<td><label class="label label-info">Age:</label></td><td>{{user.age}}</td>
					</tr>
					<tr>
						<td><label class="label label-info">Gender:</label></td><td>{{answers.gender}}</td>
					</tr>
					<tr>
						<td><label class="label label-info">Height:</label></td><td>{{answers.feet}}' {{answers.inches}} ''</td>
					</tr>
					<tr>
						<td><label class="label label-info">Favorite language:</label></td><td>{{answers.language}}</td>
					</tr>
					<tr>
						<td><label class="label label-info">Preferred stack:</label></td><td>{{answers.stack}}</td>
					</tr>
					<tr>
						<td><label class="label label-info">Religion:</label></td><td>{{answers.religion}}</td>
					</tr>
					<tr>
						<td><label class="label label-info">Smokes</label></td><td>{{answers.smoke}}</td>
					</tr>
					<tr>
						<td><label class="label label-info">Body type:</label></td><td>{{answers.body_type}}</td>
					</tr>
					<tr>
						<td><label class="label label-info">Ethnicity:</label></td><td>{{answers.ethnicity}}</td>
					</tr>
					<tr>
						<td><label class="label label-info">Wants children:</label></td><td>{{answers.wants_children}}</td>
					</tr>

				</table>
				<br>
				<!-- If this the logged-in user's profile, allow them to edit it -->
				{% if user.id == request.session.user_id %}
					<a class="btn btn-danger center-block" href="{% url 'dating:edit_user' user_id=request.session.user_id %}">Edit Profile</a>
					<a class="btn btn-danger center-block" href="{% url 'dating:edit_preference' %}">Edit Preferences</a>
				{% endif %}
			</div> <!-- #user_answers -->
		</div> <!-- .col -->

		<!-- Right Sidebar -->
		<div id="show_user_right_sidebar" class="col-sm-2">
		<!-- If this is current user's profile, show matches on the right -->
		{% if user.id == request.session.user_id %}
			<h4 class="center">People You like</h4>
			{% for l in my_like %}
			<div class="row">
				<div class="col-sm-12 user_match">
					<a href="{% url 'dating:show_user' user_id=l.like2_id %}">
						<img class="headshot center-block" src="{% static 'dating_app/'%}{{l.like2.profile_pic_url}}" alt="Denzel Washington"><br>
						<h4 class="center">{{l.like2.username}}</h4>
					</a>
				</div> <!-- .col -->
			</div><!-- .row -->
			{% endfor %}

		{% else %}
		<!-- If not user's profile, show an advertisement -->
		<div class="row">
			<div class="col-sm-12 user_match">
				<h5 class="center">Advertisement</h5>
				<a href="http://codingdojo.com">
					<img class="advertisement center-block" src="{% static 'dating_app/coding_dojo_banner_ad.png' %}" alt="Coding Dojo ad"><br>
				</a>
			</div> <!-- .col -->
		</div><!-- .row -->
		{% endif %}
		</div> <!-- .col (Left Sidebar) -->
	</div> <!-- .row -->

	<!-- Second Row: More Pictures -->

	<div id="gallery" class="row">
		<h4 class="center">More pictures of {{user.username}}</h4>
		{% for image in my_gallery %}
		<div class="col-sm-2 one_gallery_pic">
			<a href="{% static 'dating_app/' %}{{image.user_pic}}">
				<img class="show_user_pic center-block" src="{% static 'dating_app/' %}{{image.user_pic}}" alt="{{user.username}}">
				<br>
			</a>
			{% if user.id == request.session.user_id %}
				<a class="btn btn-danger center-block img_btn" href="{% url 'dating:delete_pic' image_id=image.id %}">Delete</a>
				<a class="btn btn-success center-block img_btn" href="{% url 'dating:change_profile_pic' image_id=image.id %}">Make this my profile pic</a>
			{% endif %}
		</div> <!-- .col -->
		{% endfor %}
	</div> <!-- .row -->

	<br>

	<!-- File upload -->
	{% if user.id == request.session.user_id %}
	<div id="file_upload">

		<!-- Upload image -->
		<form action="{% url 'dating:upload_pic' %}"method="post" enctype="multipart/form-data">
		<h4 class="center">Upload New Image</h4>
	    {% csrf_token %}
		    <input type="file" name="image">
		    <input class="btn btn-danger" type="submit" value="Upload">
	  	</form>
	</div>
	  	{% endif %}
	  	<br><br>
</div> <!-- #container-fluid -->
<script>
	$(document).ready(function () {
		$("#toggle_account").toggleSwitch();
		$("#toggle_account").toggleCheckedState("On")

	});
</script>